project:
  type: website
  output-dir: docs

website:
  title: "Seth&Nut"
  site-url: "fralfaro.github.io/blog/"
  favicon: 'images/logo_sn.png'
  image: 'images/logo_sn.png'
  page-footer:
    left: "Website made with [Quarto](https://quarto.org/), by Francisco Alfaro. License: [CC BY-SA 2.0](https://creativecommons.org/licenses/by-sa/2.0/)."
    right:
      - icon: github
        href: https://github.com/Seth-Nut
      - icon: linkedin
        href: https://www.linkedin.com/company/Seth-Nut/
      - icon: globe
        href: https://seth-nut.github.io/website/



  navbar:
    logo: /images/doberman.png
    right:
      - text: Nosotros
        menu:
          - text: Francisco Alfaro
            href: fran.qmd
          - text: Valeska Canales
            href: vale.qmd
      - text: Blog
        href: posts/index.qmd
      - text: Cursos
        href: teaching/index.qmd
      - text: Charlas
        href: talks/index.qmd
      #- text: Otros
      #  menu:
      #    # - text: Research (PT-BR)
      #    #   href: research/index.qmd
      #    - quarto.qmd
      #    - videos.qmd
      # - text: Resume
      #   href: https://beatrizmilz.github.io/resume/index.pdf
      # - icon: newspaper
      #   href: https://www.linkedin.com/build-relation/newsletter-follow?entityUrn=7129591797797797888
      - icon: github
        href: https://github.com/Seth-Nut
      - icon: linkedin
        href: https://www.linkedin.com/company/Seth-Nut/
      - icon: globe
        href: https://seth-nut.github.io/website/

lang: es

format:
  html:
    smooth-scroll: true
    theme:
      - pulse
      - custom.scss
    link-external-icon: false
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.beamilz\.com\/**'
    citations-hover: true
    footnotes-hover: true
    toc: true
    code-link: true

editor: visual

comments:
  giscus:
    repo: beatrizmilz/blog-en

execute:
  freeze: true
